### ISSUE TITLE
Misleading Go version in README.md

### ISSUE THREAD

**Issue by ch3nkula** [Ch3ck/bearcup#1]
The README.md file says Go version 1.7 but the link points to Go version 1.8.3. Can this be updated? :)

**Comment by Ch3ck** [comment]
Yep, missed that.

**Comment by ch3nkula** [comment]
Do what you are good at. 👍

**Comment by Ch3ck** [comment]
Fixed here: https://github.com/Ch3ck/bearcup/commit/2870890ac22aadfe0b9d09a9ea499d28be5e0191

**Comment by ch3nkula** [comment]
Thanks for fixing @Ch3ck. 👍
